#!/bin/bash
set -e

BUILD_DIR="${BUILD_DIR:-build_coverage}"
BUILD_JOBS="${BUILD_JOBS:-15}"
TEST_JOBS="${TEST_JOBS:-20}"
COVERAGE_THRESHOLD="${COVERAGE_THRESHOLD:-95}"
SKIP_HTML_REPORT="${SKIP_HTML_REPORT:-0}"
PER_FILE_GATE="${PER_FILE_GATE:-0}"

if [ ! -d "${BUILD_DIR}" ]; then
    mkdir "${BUILD_DIR}"
fi
cd "${BUILD_DIR}"

cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON -DENABLE_ASAN=OFF -DENABLE_TSAN=OFF ..

cmake --build . -j"${BUILD_JOBS}"

# Clean stale gcov data generated by previous runs (or gtest discovery), then collect from this test run only.
find . -name '*.gcda' -delete

ctest --output-on-failure -j"${TEST_JOBS}"

if [[ "$OSTYPE" == "darwin"* ]]; then
    xcrun llvm-profdata merge -sparse default.profraw -o default.profdata
    
    OBJECTS=""
    for test_bin in tests/*_test; do
        if [[ -x "$test_bin" ]]; then
             OBJECTS="$OBJECTS -object $test_bin"
        fi
    done
    
    if [ "${SKIP_HTML_REPORT}" != "1" ]; then
        xcrun llvm-cov show $OBJECTS -instr-profile=default.profdata -format=html -output-dir=coverage_report ../src
        echo "Coverage report generated in ${BUILD_DIR}/coverage_report/index.html"
    fi
    
    xcrun llvm-cov report $OBJECTS -instr-profile=default.profdata ../src
else
    if ! command -v gcovr >/dev/null 2>&1; then
        echo "gcovr is required for per-file coverage threshold checks."
        exit 1
    fi

    mkdir -p coverage_report

    if [ "${SKIP_HTML_REPORT}" != "1" ]; then
        gcovr -r .. --html -o coverage_report/index.html -j "${TEST_JOBS}" \
            --exclude-directories '.*/third' \
            --exclude-directories '.*/tests' \
            --exclude-directories '.*/build.*' \
            --exclude '(^|.*/)third/.*' \
            --exclude '(^|.*/)tests/.*' \
            --exclude '(^|.*/)main\.cpp$'
        echo "Coverage report generated in ${BUILD_DIR}/coverage_report/index.html using gcovr"
    fi

    gcovr -r .. --json-summary-pretty -o coverage_report/summary.json -j "${TEST_JOBS}" \
        --exclude-directories '.*/third' \
        --exclude-directories '.*/tests' \
        --exclude-directories '.*/build.*' \
        --exclude '(^|.*/)third/.*' \
        --exclude '(^|.*/)tests/.*' \
        --exclude '(^|.*/)main\.cpp$'

    python3 - "$COVERAGE_THRESHOLD" "$PER_FILE_GATE" <<'PY'
import json
import sys

threshold = float(sys.argv[1])
per_file_gate = sys.argv[2] == "1"
with open("coverage_report/summary.json", "r", encoding="utf-8") as f:
    data = json.load(f)

files = data.get("files", [])
if not files:
    print("No files found in gcovr summary, failing coverage gate.")
    sys.exit(1)

failed = []
checked = 0
sum_total = 0
sum_covered = 0

for entry in files:
    name = entry.get("filename", "")
    if name.startswith("third/") or name.startswith("tests/"):
        continue
    if name.endswith("main.cpp"):
        continue

    line_total = entry.get("line_total")
    line_covered = entry.get("line_covered")
    line_percent = entry.get("line_percent")

    if line_total is None:
        line_total = entry.get("lines_total")
    if line_covered is None:
        line_covered = entry.get("lines_covered")
    if line_percent is None and line_total:
        line_percent = (float(line_covered) * 100.0) / float(line_total)
    elif line_percent is not None and line_percent <= 1.0:
        line_percent = float(line_percent) * 100.0

    if not line_total:
        continue

    sum_total += int(line_total)
    sum_covered += int(line_covered)
    checked += 1
    if line_percent < threshold:
        failed.append((name, line_percent, line_covered, line_total))

if checked == 0:
    print("No non-empty source files checked, failing coverage gate.")
    sys.exit(1)

overall_pct = (float(sum_covered) * 100.0) / float(sum_total)
print(f"Overall project coverage: {overall_pct:.2f}% ({sum_covered}/{sum_total})")
if overall_pct < threshold:
    print(f"Overall coverage gate failed (< {threshold:.2f}%).")
    sys.exit(1)

if failed:
    header = "Per-file coverage gate failed" if per_file_gate else "Per-file coverage below threshold (warning only)"
    print(f"{header} (< {threshold:.2f}%):")
    for name, pct, covered, total in sorted(failed, key=lambda x: x[1]):
        print(f"  {name}: {pct:.2f}% ({covered}/{total})")
    if per_file_gate:
        sys.exit(1)

print(f"Coverage gate passed: {checked} files checked, threshold={threshold:.2f}%")
PY
fi
